/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_linkedlist_free: (a: number, b: number) => void;
export const __wbg_storageengine_free: (a: number, b: number) => void;
export const linkedlist_clear: (a: number) => void;
export const linkedlist_delete: (a: number, b: number) => number;
export const linkedlist_generate_random: (a: number, b: number, c: number) => void;
export const linkedlist_insert_sorted: (a: number, b: number) => void;
export const linkedlist_length: (a: number) => number;
export const linkedlist_new: () => number;
export const linkedlist_push_front: (a: number, b: number) => void;
export const linkedlist_search: (a: number, b: number) => number;
export const linkedlist_snapshot: (a: number) => [number, number];
export const linkedlist_sort: (a: number) => void;
export const storageengine_config: (a: number) => [number, number];
export const storageengine_create_table: (a: number, b: number, c: number, d: number, e: number) => [number, number, number];
export const storageengine_delete: (a: number, b: number, c: number, d: number, e: number) => [number, number, number];
export const storageengine_drop_table: (a: number, b: number, c: number) => number;
export const storageengine_flush_all: (a: number) => void;
export const storageengine_flush_page: (a: number, b: number) => number;
export const storageengine_get: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
export const storageengine_insert: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
export const storageengine_list_tables: (a: number) => [number, number];
export const storageengine_new: (a: number, b: number) => [number, number, number];
export const storageengine_scan: (a: number, b: number, c: number) => [number, number, number, number];
export const storageengine_snapshot_buffer_pool: (a: number) => [number, number];
export const storageengine_snapshot_disk: (a: number) => [number, number];
export const storageengine_snapshot_page: (a: number, b: number) => [number, number];
export const storageengine_snapshot_table: (a: number, b: number, c: number) => [number, number];
export const storageengine_table_schema: (a: number, b: number, c: number) => [number, number];
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
